# Generated by Django 3.2.6 on 2023-07-26 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0008_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
    ]
