# Generated by Django 4.2.3 on 2023-07-26 09:21

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0009_remove_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=10000, verbose_name='Текст'),
        ),
    ]
